package Parser::parse_options;

use strict;
use Exporter 'import';
use Getopt::Long::Descriptive;

our @EXPORT_OK = qw(parse_options);

# Function that will parse the user options 
sub parse_options {
    my @args = @_;

    # Extend how far description text goes across the screen before wrapping
    $Getopt::Long::Descriptive::TERM_WIDTH = 120;

    # Declare lexical variables closed over by validation callbacks
    my %sexes         = ( "FID" => 1, "IID" => 2, "SEX" => 3, "MALE" => 1, "FEMALE" => 2 );
    my %affections    = ( "FID" => 1, "IID" => 2, "AFFECTION" => 3, "AFFECTION_VALUE" => 2 );
    my %ages          = ( "FID" => 1, "IID" => 2, "AGE" => 3 );
    my %ibd_estimates = ( "FID1" => 1, "IID1" => 2, "FID2" => 3, "IID2" => 4, "IBD0" => 7, "IBD1" => 8, "IBD2" => 9, "PI_HAT" => 10 );
    my %mito_matches  = ( "FID1" => 1, "IID1" => 2, "FID2" => 3, "IID2" => 4, "MATCH" => 5, "MATCH_VAL" => 1 );
    my %y_matches     = ( "FID1" => 1, "IID1" => 2, "FID2" => 3, "IID2" => 4, "MATCH" => 5, "MATCH_VAL" => 1 );
    my @ref_pops;
    my @onekg_pops    = ("ACB", "ASW", "BEB", "CDX", "CEU", "CHB", "CHS", "CLM", "ESN", "FIN", "GBR", "GIH", "GWD", "IBS", "ITU", "JPT", "KHV", "LWK", "MSL", "MXL", "PEL", "PJL", "PUR", "STU", "TSI", "YRI");
    my @trait_order;
    my %traits;
    my $data_stem = "";

    my ($opt, $usage)= describe_options(
        "Usage: compadre_kickoff.pl %o",                                  
            
            [ "For usage and documentation:" ],  
            [ 'help|h|?', "Brief help message", { shortcircuit => 1 } ],      
            [ 'man', "Print manual page", { shortcircuit => 1 } ],    
            [],
            [ "Required options (one of the following):" ],
            [ 'plink_ibd|p=s', "Specify path to a .genome IBD estimates file produced by PLINK" ],
            [ 'input|i=s%', "Specify path to an IBD estimates file and additional column information (Ex. FILE=test.txt IBD0=5 IBD1=6 )" ],
            [],
            [ "    (or both):" ],
            [ 'file|bfile|ped|map=s', "Path to PLINK formatted input data stem (automatically strips extensions)" ],
            [ 'genome', "Read in --file and calculate IBD estimates using PLINK" ],  
            [],
            [ "COMPADRE options (new):" ],
            [ 'segment_data=s', "Shared segments data in format readable by ERSA (see full documentation)" ], 
            [ 'port_number=i', "Port number for additional Python computation ", { default => 6000 , default_needed => 1 } ],  
            [ 'run_padre', "Run PADRE after standard pedigree reconstruction is complete", { default => 0 } ],
            [],
            [ "General options:" ],
            [ 'rel_threshold|t=f', "Set the minimum level of relatedness for two people to be considered related", {  default => 0.09375, default_needed => 1 } ],
            [ 'degree_rel_cutoff=i', "Set the maximum degree of relatedness for two people to be considered related", { default => 3, default_needed => 1} ],  
            [ 'output_dir|o=s', "Specify path to the output directory for all results" ],   
            [ 'verbose|v=i', "Set verbosity level (0=none; 1=default; 2=more; 3=max)", { default => 1, default_needed => 1 } ], 
            [ 'lib=s', "Path to the lib directory" ],
            [ 'bin=s', "Path to the bin directory" ],
            [],
            [ "prePRIMUS IBD estimation options:" ],
            [ 'plink_ex=s', "Path to the plink executable file (searches environment variables by default)" ],
            [ 'ref_pops=s', "Comma separated list of 1000 Genomes populations used for reference allele freqs (overrides default method)" ],
            [ 'no_automatic_IBD', "Turn off automatic selection of the HapMap3 populations for reference allele freqs (On by default)", { default => 1 } ],    
            [ 'remove_AIMs', "Automatically remove ancestry informative markers", { default => 0 } ],  
            [ 'keep_AIMs', "Do not remove ancestry informative markers", { default => 0 } ],   
            [ 'internal_ref', "Use the dataset provided in --file to get reference allele frequencies", { default => 0 } ],
            [ 'alt_ref_stem=s', "Path to PLINK formatted data (no file extensions) used for allele frequencies" ],   
            [ 'keep_inter_files', "Keep prePRIMUS intermediate files" ],  
            [ 'rerun', "Rerun prePRIMUS pipeline even if output already exists" ],
            [ 'no_mito=i', "Disable mitochondrial data (1 to disable, 0 to enable)", { default => 1 } ],  
            [ 'no_y=i', "Disable y data (1 to disable, 0 to enable)", { default => 1 } ],  
            [ 'min_pihat_threshold=f', "Set a minimum pi-hat threshold that will be used in the plink", { default => 0, default_needed => 1 } ], 
            [ 'gzip_genome', "Request gzipped output for the .genome generated by the PLINK ibd detection (off by default)" ], 
            [ 'reference_pop', "Reference populations"],
            [ 'samples=s', "A file containing a list of all samples (e.g., a .fam file) to ensure individuals with no relatives are included" ],   
            [ 'max_memory=i', "Specify amount of memory to be used in PLINK prePRIMUS commands (in MB)" ],
            [ 'no_PCA_plot', "Forgo running pca and getting PCA plots in order to get a faster runtime", { default => 0, default_needed => 1} ],   
            [],
            [ "Identification of maximum unrelated set (IMUS) options:" ],
            [ 'no_IMUS', "Don't identify a maximum unrelated set", { default => 1} ], 
            [ 'missing_val=f', "Set value that denotes missing data in trait files", { default => 0, default_needed => 1} ],  
            [ 'size', "Specify to weight on set size (Default unless a binary trait is specified first)" ], 
            [ 'high_btrait=s', "File with FID, IID, and binary trait to weight for the higher value" ],  
            [ 'low_btrait=s', "File with FID, IID, and binary trait to weight for the lower value" ],                           
            [ 'high_qtrait=s', "File with FID, IID, and quantitative trait to weight for higher values" ],                   
            [ 'low_qtrait=s', "File with FID, IID, and quantitative trait to weight for lower values" ],                     
            [ 'mean_qtrait=s', "File with FID, IID, and quantitative trait to weight towards the mean value" ],                   
            [ 'tails_qtrait=s', "File with FID, IID, and quantitative trait to weight against the middle values" ],   
            [ 'generate_likelihoods_only', "only generate the likelihood vectors", { default => 0 }],
            [],
            [ "Pedigree Reconstruction (PR) options:" ],
            [ 'no_PR', "Don't reconstruct pedigrees" ],   
            [ 'max_gens=i', "Max number of generations sampled in reconstructed pedigree" ],
            [ 'max_gen_gap=i', "Max number of generations between two people that have a child", { default => 0 } ],  
            [ 'age_file=s', "Specify path to the file containing the age of each sample" ],   
            [ 'ages=s%', "Like --age_file but requires FILE=[file], optional specification of file columns" ],
            [ 'sex_file=s', "Specify path to the file containing the sex of each sample" ],  
            [ 'sexes=s%', "Like --sex_file but requires FILE=[file], optional specification of file columns" ],
            [ 'mito_data|mito_matches|mito=s%', "Path to mito matching status for each pair of samples (requires FILE=[file])" ],
            [ 'y_data|y_matches|y=s%', "Path to y matching status for each pair of samples (requires FILE=[file])" ],
            [ 'MT_error_rate=f', "Proportion of the MT sequence that must not match to be called a non-match", { default => 0.01, default_needed => 1 } ],
            [ 'Y_error_rate=f', "Proportion of the Y sequence that must not match to be called a non-match", { default => 0.01, default_needed => 1 } ],   
            [ 'use_mito_match=i', "Ensures that the final reconstructed pedigree complies with the MT matching rules", { default => 0 }],
            [ 'use_y_match=i', "Ensures that the final reconstructed pedigree complies with the y chromosome matching rules", { default => 0 }],  
            [ 'affection_file=s', "Specify path to the file containing the affection status of each sample" ], 
            [ 'affections=s%', "Like --affection_file; need FILE=[file], optional specification of file columns" ],
            [ 'int_likelihood_cutoff=f', "Initial minimum likelihood for a relationship to reconstruction", { default => 0.1, default_needed => 1 } ],  
            [],
            [ "ERSA options:" ],
            [ 'min_cm=f', "minimum segment size to consider", { default => 2.5, default_needed => 1 } ], 
            [ 'max_cm=f', "maximum segment size to consider for estimating the exponential distribution of segment sizes in the population", { default => 10.0, default_needed => 1 } ],
            [ 'max_meioses=i', "maximum number of meioses to consider", { default => 40, default_needed => 1 } ], 
            [ 'rec_per_meioses=f', "expected number of recombination events per meioses", { default => 35.2548101, default_needed => 1 } ],   
            [ 'ascertained_chromosome=s', "Ascertained chromosome", { default => 'no_ascertainment', default_needed => 1 } ],  
            [ 'ascertained_position=i', "chromosomal position of ascertained disease locus" ],
            [ 'control_files=s', "GERMLINE or Beagle fibd output file(s) for population control" ],  
            [ 'control_sample_size=i', "Sample size of control population. Used with --control_files flag" ], 
            [ 'exp_mean=f', "Mean of exp distribution of shared segment size in population", { default => 3.197036753, default_needed => 1} ],
            [ 'pois_mean=f', "Mean of the Poisson distribution of the number of segments shared between a pair of individuals in the population", { default => 13.73, default_needed => 1 } ],
            [ 'pair_file=s', "Restrict pairwise comparisons to the ID pairs specified i this file" ],
            [ 'single_pair', "Restrict pairwise comparisons to the pairs specified in this flag (id1:id2)" ],
            [ 'number_of_ancestors=i', "Restrict relationships to [1] one parent (half-sibs/cousins), [2] two parents (full-sibs/cousins), or [0] (parent-offspring/grandparent-granchild).", { default => 'None' } ], 
            [ 'number_of_chromosomes=i', "Number of chromosomes", { default => 22, default_needed => 1 } ], 
            [ 'parent_offspring_option', "Option to evaluate potential parent-offspring and sibling relationships based on total proportion of the genome that is shared ibd1", { default => 1, default_needed => 1 } ],                                                      
            [ 'parent_offspring_zscore=f', "Z-score for rejecting a sibling relationship in favor of a parent-offspring relationship (alpha=0.01)", { default => 2.33, default_needed => 1 } ], 
            [ 'adjust_pop_dist', "Option to adjust the population distribution of shared segments downward for segments that could not be detected due to recent ancestry", { default => 0, default_needed => 1 } ],  
            [ 'confidence_level=f', "Confidence level for confidence interval around the estimated degree of relationship.", { default => 0.95, default_needed => 1 } ], 
            [ 'mask_common_shared_regions', "excludes chromosomal regions that are commonly shared from evaluation. Used only when the control_files or mask_region_file parameter is specified", { default => 0, default_needed => 1 } ],  
            [ 'mask_region_cross_length=i', "length in base pairs that a shared segment must extend past a masked segment in order to avoid truncation. Used only when mask_common_shared_regions parameter is specified ", { default => 1000000, default_needed => 1 } ],   
            [ 'mask_region_file=s', "file containing chromosomal regions to exclude from evaluation." ], 
            [ 'mask_region_threshold=f', "Threshold for the ratio of observed vs. expected segment sharing in controls before a region will be masked.", { default => 4.0, default_needed => 1 } ], 
            [ 'mask_region_sim_count=i', "number of simulations performed of the null distribution of shared segment locations in controls; results written to output_file.sim", { default => 0, default_needed => 1 } ], 
            [ 'recombination_files=s', "file containing genetic distances for all chromosomes. This parameter must be specified with Beagle fibd input files" ], 
            [ 'beagle_markers_files=s', "Beagle marker files (one file required for each chromosome, wildcards required, ex: chr*beagle.marker). Each filename must begin with the chromosome name followed by a period. This parameter must be specified with Beagle fibd input files" ],     
            [ 'ersa_model_output=s', "ERSA will generate this file when the --model_output_file option specified on the commandline when running ERSA. For each pair of individuals in the dataset, it will contain the likelihood that they are related as 1st through 40th degree relatives sharing 0, 1, or two parents in common at each degree. PRIMUS uses these likelihhods and the likelihood that they are unrelated (obtained from the file specified with the --ersa_results option) to find the most likely way each family network is connected." ],  
            [ 'ersa_results=s', "ERSA's main output file (specified with the --output_file option) needs to be provided. PRIMUS + ERSA uses the likelihood that a pair of individuals are unrelated in its algorithm. Provide the path to the file here." ],
            [ 'project_summary_file=s', "The project level summary file is in the main output directory which we call the Project level directory (default is *_PRIMUS). In the main ouput directory, there are two summary files. One is a summary containing the pairwise relationship table (*_pairwuse_table.txt), and this is NOT the file you want to provide with this option. You want to provide the other summary file." ],             
            [ 'PADRE_multiple_test_correct', "PADRE multiple testing correction", { default => 0, default_needed => 1} ],   
            { argv => \@args }                                                             
        );

    # Handle cases where the user passed the help flag or they passed the man flag
    if ($opt->help) {
        print $usage->text;
        exit 0;
    }
    # We are going to run the man documentation for the compadre_kickoff.pl 
    if ($opt->man) {
        require Pod::Usage;
        Pod::Usage::pod2usage({ -input => $0, -verbose => 2 }); 
    }

    # Extract data_stem and build trait structures from options
    if (defined $opt->file) {
        my $val = $opt->file;
        if ($val =~ /\.ped$/i) {
            $data_stem = $val;
            $data_stem =~ s/\.ped$//i;
        } elsif ($val =~ /\.map$/i) {
            $data_stem = $val;
            $data_stem =~ s/\.map$//i;
        } else {
            $data_stem = $val;
        }
    }
    if ($opt->size) {
        push(@trait_order, "size");
        $traits{'size'} = "-size";
    }
    if (defined $opt->high_btrait) {
        my $val = $opt->high_btrait;
        push(@trait_order, $val);
        $traits{$val} = "high_btrait";
    }
    if (defined $opt->low_btrait) {
        my $val = $opt->low_btrait;
        push(@trait_order, $val);
        $traits{$val} = "low_btrait";
    }
    if (defined $opt->high_qtrait) {
        my $val = $opt->high_qtrait;
        push(@trait_order, $val);
        $traits{$val} = "high_qtrait";
    }
    if (defined $opt->low_qtrait) {
        my $val = $opt->low_qtrait;
        push(@trait_order, $val);
        $traits{$val} = "low_qtrait";
    }
    if (defined $opt->mean_qtrait) {
        my $val = $opt->mean_qtrait;
        push(@trait_order, $val);
        $traits{$val} = "mean_qtrait";
    }
    if (defined $opt->tails_qtrait) {
        my $val = $opt->tails_qtrait;
        push(@trait_order, $val);
        $traits{$val} = "tails_qtrait";
    }

    #TODO: move the validation functions into their own functions
    # Follow if statements all check if the provided arguments are 
    # valid. If they are not valid then the code exits and prints an error message with the help message underneath it
    # Validate and process --ref_pops
    if (defined $opt->ref_pops) {
        @ref_pops = split(/,/, $opt->ref_pops);
        @ref_pops = map { uc($_) } @ref_pops;
        foreach my $pop (@ref_pops) {
            next if $pop =~ /none/i;
            if (!grep { $_ eq $pop } @onekg_pops) {
                $usage->die({ msg => "\n\n[COMPADRE] Error: Invalid 1KG population: $pop\n" . "Must be a comma seperated list these: @onekg_pops\n" . "For example: --ref_pops CEU,TSI,YRI\n\n" });
            }
        }
    }

    # Validate and process --input
    if (defined $opt->input) {
        my @possible_keys = qw(FILE FID1 IID1 FID2 IID2 IBD0 IBD1 IBD2 PI_HAT RELATEDNESS);
        my $input_hash = $opt->input;
        foreach my $raw_key (keys %$input_hash) {
            my $value = $input_hash->{$raw_key};
            my $key = uc($raw_key);
            if (grep { $_ eq $key } @possible_keys) {
                $ibd_estimates{$key} = $value;
            } else {
                $usage->die({ msg => "\n\n[COMPADRE] Error: Invalid key '$key' before \"=\" for --input.\n" . "Must be one of these: " . join(', ', @possible_keys) . "\n\n" });
            }
        }
    }

    # Validate and process --ages
    if (defined $opt->ages) {
        my @possible_keys = qw(FILE FID IID AGE);
        my $input_hash = $opt->ages;
        foreach my $raw_key (keys %$input_hash) {
            my $value = $input_hash->{$raw_key};
            my $key = uc($raw_key);
            if (grep { $_ eq $key } @possible_keys) {
                $ages{$key} = $value;
            } else {
                $usage->die({ msg => "\n\n[COMPADRE] Error: Invalid key '$key' for --ages option.\n" . "Must be one of these: " . join(', ', @possible_keys) . "\n\n" });
            }
        }
    }

    # Validate and process --sexes
    if (defined $opt->sexes) {
        my @possible_keys = qw(FILE FID IID SEX MALE FEMALE);
        my $input_hash = $opt->sexes;
        foreach my $raw_key (keys %$input_hash) {
            my $value = $input_hash->{$raw_key};
            my $key = uc($raw_key);
            if (grep { $_ eq $key } @possible_keys) {
                $sexes{$key} = $value;
            } else {
                $usage->die({ msg => "\n\n[COMPADRE] Error: Invalid key '$key' for --sexes option.\n" . "Must be one of these: " . join(', ', @possible_keys) . "\n\n" });
            }
        }
    }

    # Validate and process --mito_data
    if (defined $opt->mito_data) {
        my @possible_keys = qw(FILE FID1 IID1 FID2 IID2 MATCH MATCH_VAL);
        my $input_hash = $opt->mito_data;
        foreach my $raw_key (keys %$input_hash) {
            my $value = $input_hash->{$raw_key};
            my $key = uc($raw_key);
            if (grep { $_ eq $key } @possible_keys) {
                $mito_matches{$key} = $value;
            } else {
                $usage->die({ msg => "\n\n[COMPADRE] Error: Invalid key '$key' before \"=\" for --mito_data.\n" . "Must be one of these: " . join(', ', @possible_keys) . "\n\n" });
            }
        }
    }

    # Validate and process --y_data
    if (defined $opt->y_data) {
        my @possible_keys = qw(FILE FID1 IID1 FID2 IID2 MATCH MATCH_VAL);
        my $input_hash = $opt->y_data;
        foreach my $raw_key (keys %$input_hash) {
            my $value = $input_hash->{$raw_key};
            my $key = uc($raw_key);
            if (grep { $_ eq $key } @possible_keys) {
                $y_matches{$key} = $value;
            } else {
                $usage->die({ msg => "\n\n[COMPADRE] Error: Invalid key '$key' before \"=\" for --y_data.\n" . "Must be one of these: " . join(', ', @possible_keys) . "\n\n" });
            }
        }
    }

    # Validate and process --affections
    if (defined $opt->affections) {
        my @possible_keys = qw(FILE FID IID AFFECTION AFFECTION_VALUE);
        my $input_hash = $opt->affections;
        foreach my $raw_key (keys %$input_hash) {
            my $value = $input_hash->{$raw_key};
            my $key = uc($raw_key);
            if (grep { $_ eq $key } @possible_keys) {
                $affections{$key} = $value;
            } else {
                $usage->die({ msg => "\n\n[COMPADRE] Error: Invalid key '$key' before \"=\" for --affections option.\n" . "Must be one of these: " . join(', ', @possible_keys) . "\n\n" });
            }
        }
    }

    # Integrate option overrides back into validation hashes
    # Later in the codebase, it looks for this FILE key 
    # from the arrays
    $sexes{'FILE'} = $opt->sex_file if defined $opt->sex_file;
    $ages{'FILE'} = $opt->age_file if defined $opt->age_file;
    $affections{'FILE'} = $opt->affection_file if defined $opt->affection_file;
    $ibd_estimates{'FILE'} = $opt->plink_ibd if defined $opt->plink_ibd;

    if (exists $ibd_estimates{'RELATEDNESS'}) {
        $ibd_estimates{'PI_HAT'} = $ibd_estimates{'RELATEDNESS'};
    }

    # Adjust trait priority and defaults
    if (defined $trait_order[0] && $traits{$trait_order[0]} =~ /qtrait/) {
        unshift(@trait_order, "size");
    }
    if (!grep { $_ eq "size" } @trait_order) {
        push(@trait_order, "size");
        $traits{'size'} = "size";
    }

    # Initialize your default configuration object
    my $config = {
        global => {
            verbose         => $opt->verbose,
            study_name      => "",
            dataset_name    => "",
            output_dir      => $opt->output_dir // "",
            port_number     => $opt->port_number,
            run_padre       => $opt->run_padre,
            log_file        => undef,
            debug           => 0,
            test            => 0,
            cluster         => 0,
            public_html_dir => "",
            lib_dir         => $opt->lib // "",
            bin_dir         => $opt->bin // "",
            usage           => $usage, # Store the usage object right here
        },
        imus => {
            sexes                            => \%sexes,
            affections                       => \%affections,
            ages                             => \%ages,
            traits                           => \%traits,
            trait_order                      => \@trait_order,
            relatedness_threshold            => $opt->rel_threshold,
            degree_rel_cutoff                => $opt->degree_rel_cutoff,
            initial_likelihood_cutoff        => $opt->int_likelihood_cutoff,
            max_generations                  => $opt->max_gens // "none",
            max_generation_gap               => $opt->max_gen_gap,
            missing_data_value               => $opt->missing_val,
            get_max_unrelated_set            => $opt->no_imus,
            reconstruct_pedigrees            => $opt->no_pr,
            generate_likelihood_vectors_only => $opt->generate_likelihoods_only,
            ibd_estimates                    => \%ibd_estimates,
            mito_matches                     => \%mito_matches,
            y_matches                        => \%y_matches,
        },
        preprimus => {
            run_prePRIMUS                     => $opt->genome ? 1 : 0,
            data_stem                         => $data_stem,
            plink_path                        => $opt->plink_ex // "plink",
            no_automatic_IBD                  => $opt->no_automatic_ibd,
            remove_AIMs                       => $opt->remove_aims,
            keep_AIMs                         => $opt->keep_aims,
            no_mito                           => $opt->no_mito,
            no_y                              => $opt->no_y,
            use_mito_match                    => $opt->use_mito_match,
            use_y_match                       => $opt->use_y_match,
            MT_MAX_PERCENT_DIFFERENCE_FOR_MATCH => $opt->mt_error_rate,
            Y_MAX_PERCENT_DIFFERENCE_FOR_MATCH  => $opt->y_error_rate,
            internal_ref                      => $opt->internal_ref,
            alt_ref_stem                      => $opt->alt_ref_stem // "",
            keep_prePRIMUS_intermediate_files => $opt->keep_inter_files,
            no_PCA_plot                       => $opt->no_pca_plot,
            ref_pops                          => $opt->ref_pops,
            reference_pop                     => $opt->reference_pop // "",
            rerun                             => $opt->rerun // 0,
            min_pihat_threshold               => $opt->min_pihat_threshold,
            samples_file                      => $opt->samples,
            gzip_genome                       => $opt->gzip_genome,
            max_memory                        => $opt->max_memory,
        },
        padre => {
            run_PRIMUS_plus_ERSA        => 0,
            ersa_model_output           => $opt->ersa_model_output // "",
            ersa_results                => $opt->ersa_results // "",
            project_summary_file        => $opt->project_summary_file // "",
            PADRE_multiple_test_correct => $opt->padre_multiple_test_correct // 0,
        },
        ersa => {
            min_cm                      => $opt->min_cm,
            max_cm                      => $opt->max_cm,
            max_meioses                 => $opt->max_meioses,
            rec_per_meioses             => $opt->rec_per_meioses,
            ersa_data                   => $opt->segment_data,
            ascertained_chromosome      => $opt->ascertained_chromosome,
            ascertained_position        => $opt->ascertained_position,
            control_files               => $opt->control_files,
            control_sample_size         => $opt->control_sample_size,
            exp_mean                    => $opt->exp_mean,
            pois_mean                   => $opt->pois_mean,
            number_of_ancestors         => $opt->number_of_ancestors,
            number_of_chromosomes       => $opt->number_of_chromosomes,
            parent_offspring_option     => $opt->parent_offspring_option,
            parent_offspring_zscore     => $opt->parent_offspring_zscore,
            adjust_pop_dist             => $opt->adjust_pop_dist,
            confidence_level            => $opt->confidence_level,
            mask_common_shared_regions  => $opt->mask_common_shared_regions,
            mask_region_cross_length    => $opt->mask_region_cross_length,
            mask_region_file            => $opt->mask_region_file,
            mask_region_threshold       => $opt->mask_region_threshold,
            mask_region_sim_count       => $opt->mask_region_sim_count,
            recombination_files         => $opt->recombination_files,
            beagle_markers_files        => $opt->beagle_markers_files,
        }
    };
    # make sure both the --file nad --genome are provided if the user wishes to run prePRIMUS
    if ($data_stem ne "" && $config->{preprimus}->{run_prePRIMUS} != 1) {
      die "INVALID INPUT OPTIONS: --file input also requires the --genome flag to run.\n\n";
    }

    # Make sure that we provide segment data for running padre
    if($config->{padre}->{run_padre} && $config->{ersa}->{ersa_data} eq "")
    {
      die "\n[COMPADRE] Error: --run_padre requires --segment_data to be specified.\n\n";
    }

    # Update PRIMUS+ERSA run mode if needed for compadre. To 
    # simplify branching we are going to see if the files are found here
    my $model_output_provided = ($config->{padre}->{ersa_model_output} ne "");
    my $results_provided = ($config->{padre}->{ersa_results} ne "");
    my $total_files_found = $model_output_provided + $results_provided;

    # We only want to run PRIMUS_plus_ERSA if both files are provided
    # If neither file is provided than we skip this part
    if ($total_files_found == 2) {
        if (($config->{padre}->{project_summary_file} eq "") eq "" && !exists $ibd_estimates{'FILE'} && $data_stem eq "") {
            die "INVALID INPUTS: PRIMUS+ERSA requires a PRIMUS project summary file; either provide one on the commandline or generate one by running PRIMUS.\n\n";
        }
        $config->{padre}->{run_PRIMUS_plus_ERSA} = 1; 
    } elsif ($total_files_found == 1){
        die "INVALID INPUTS: PRIMUS+ERSA requires both the model_output file and the results files output by ERSA.\n\n";
    }

    # Check if both primary inputs are missing
    if (!exists $ibd_estimates{'FILE'} && $data_stem eq "") {
        if (!$config->{padre}->{run_PRIMUS_plus_ERSA}) {
            $usage->die({ msg => "\n[COMPADRE] No input data provided. Please run with the --help flag for details.\n\n" });
        } else {
            $config->{imus}->{reconstruct_pedigrees} = 0;
            $config->{imus}->{get_max_unrelated_set} = 0;
        }
    }

    # 3. Check if the specified IBD input file exists
    if (exists $ibd_estimates{'FILE'} && !-e $ibd_estimates{'FILE'}) {
        if (!$config->{preprimus}->{run_prePRIMUS} && !$config->{padre}->{run_PRIMUS_plus_ERSA}) {
            print "[COMPADRE] Error: IBD INPUT FILE DOES NOT EXIST: $ibd_estimates{'FILE'}\n";
            exit 2;
        }
    }

    # 4. Handle prePRIMUS specific resolution and study_name/output_dir derivations
    if ($config->{preprimus}->{run_prePRIMUS}) {
        if (exists $ibd_estimates{'FILE'}) {
            die "[COMPADRE] Error: If you already have IBD estimates, then you don't need to calculate new ones with --genome option. If you do need to calculate IBD estimates, don't input anything for the IBD estimates.\n\n";
        }
        require PRIMUS::prePRIMUS_pipeline_v7;
        $config->{global}->{study_name} = PRIMUS::prePRIMUS_pipeline_v7::get_file_name_from_stem($data_stem);
        $config->{global}->{output_dir} = "${data_stem}_PRIMUS" if $config->{global}->{output_dir} eq "";
    }

    # Set fallback output directory if not passed in
    if ($config->{global}->{output_dir} eq "" && exists $ibd_estimates{'FILE'}) {
        $config->{global}->{output_dir} = "$ibd_estimates{'FILE'}_PRIMUS";
    }

    # Ultimate fallback for output_dir to ensure it is never empty
    if ($config->{global}->{output_dir} eq "") {
        # This specifically is the case where the user wishes to 
        # run PADRE (also referred to as PRIMUS plus ERSA)
        if (($config->{padre}->{project_summary_file} // "") ne "") {
            my ($volume, $directories, $file) = File::Spec->splitpath($opt->project_summary_file);
            my $summary_dir = File::Spec->catpath($volume, $directories, "");
            if ($summary_dir ne "") {
                $config->{global}->{output_dir} = $summary_dir;
            } else {
                $config->{global}->{output_dir} = "PRIMUS_plus_ERSA_results";
            }
        } else {
            $config->{global}->{output_dir} = "COMPADRE_results";
        }
    }

    # Set fallback dataset_name if IBD estimates file is provided
    if (exists $ibd_estimates{'FILE'}) {
        if ($ibd_estimates{'FILE'} =~ /\/([^\/]+)$/) {
            $config->{global}->{dataset_name} = $1;
        } else {
            $config->{global}->{dataset_name} = $ibd_estimates{'FILE'};
        }
    }

    # 6. Formulate canonical path for the log file
    $config->{global}->{log_file} = File::Spec->catfile($config->{global}->{output_dir}, "COMPADRE_output.log");


    # 8. Ensure relatedness threshold and degree rel cutoff are synchronized
    # These configs have default values so we don't need to specify default 
    # values here.
    my $relatedness_threshold = $config->{imus}->{relatedness_threshold};
    my $degree_rel_cutoff     = $config->{imus}->{degree_rel_cutoff};

    if ($relatedness_threshold != 0.09375 || $degree_rel_cutoff != 3) {
        if ($degree_rel_cutoff == 3) {
            $degree_rel_cutoff = 3 if $relatedness_threshold <= 0.1;
            $degree_rel_cutoff = 2 if $relatedness_threshold > 0.1 && $relatedness_threshold <= 0.2;
            $degree_rel_cutoff = 1 if $relatedness_threshold > 0.2;
        } elsif ($degree_rel_cutoff == 2) {
            $relatedness_threshold = 0.1875;
        } elsif ($degree_rel_cutoff == 1) {
            $relatedness_threshold = 0.375;
        } else {
            die "INVALID value for -d|--degree_rel_cutoff; Valid options are integers from 1 to 3\n\n";
        }
        $config->{imus}->{relatedness_threshold} = $relatedness_threshold;
        $config->{imus}->{degree_rel_cutoff} = $degree_rel_cutoff;
    }

    return $config;
}
